### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by spekulatius**
Hey @nicolas-racchi 

just a typo...

Cheers!

### CODE REVIEW

**Comment by nicolas-racchi** [comment]
Thank you ✌️✌️

**Comment by spekulatius** [comment]
No worries, happy to help out!

**Comment by nicolas-racchi** [comment]
Your articles have been really useful!

Have a nice day

**Comment by spekulatius** [comment]
🤩️ Thank you!  Let me know if you got any feedback on my articles :+1: 

Btw, that's how I found your repo - your link showed up :)

**Pull request merged**
